### PR TITLE
Fix Safari issue with no titles for history item

### PR DESCRIPTION
**Pull request by rmartine-ias**
# Description

Some Safari entries have no title. If this is the case, and they have
the same URL and datetime, then we can't sort them. Python doesn't allow
comparing strings and None.

This uses the solution here:
<https://stackoverflow.com/questions/60695318/sort-a-list-of-tuples-with-none-values-in-python3>

It does not affect the output. If the datetime were to ever be None,
this could cause an issue, potentially.

The diff is large because of running black/fixing flake8 issues so the pre-commit hooks pass.

Fixes: https://github.com/browser-history/browser-history/issues/272

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have read the [contribution guidelines](https://browser-history.readthedocs.io/en/latest/contributing.html) and followed it as far as possible. 
- [x] I have performed a self-review of my own code (if applicable)
- [x] I have commented my code, particularly in hard-to-understand areas (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings 
- [x] I have enabled the pre-commit hook and it's not detecting any issue.
- [x] Any dependent and pending changes have been merged and published

### CODE REVIEW

**Review by Samyak2 — APPROVED** [review]
Thank you for the fix (and for reporting the issue)!

**Comment by Samyak2** [comment]
Could you rebase the PR on the base branch? I've pushed a commit that might fix the failing CI

**Comment by Samyak2** [comment]
Could you add a test case that has `None` values which was causing the failure?

I can add it in a few days if you don't have the time/bandwidth for it

**Comment by rmartine-ias** [comment]
hmm, looked at the tests a bit, don't think I will be able to add in the coming week or so at least, unfortunately

the offending URLs, for your perusal:
```
https://github.com/login/oauth/authorize?client_id=<REDACTED>&scope=user:email,read:org&state=<REDACTED>
https://integralads.okta.com/enduser/callback?code=<REDACTED>&state=<REDACTED>
https://github.com/sessions/two-factor/app
https://github.com/riley-martine/vim-theme-work
https://github.com/sessions/two-factor
https://www.google.com/search?client=safari&rls=en&q=bash+declare+-A&ie=UTF-8&oe=UTF-8
https://stackoverflow.com/questions/47231003/declare-array-in-bash-script-errors-out-bad-array-subscript?lastactivity
http://www.erhanbirol.com/othersites/linux-e.com/data/declare.simple.bash.array.example.txt
https://www.google.com/search?client=safari&rls=en&q=github+use+ssh+instead+of+http&ie=UTF-8&oe=UTF-8
https://github.com/sessions/two-factor/webauthn
```

The stackoverflow link seems replicable; with 0.4.0 of browser-history, I can open safari, visit it, close safari, run `browser-history -b Safari` with the following added to line 290 of `generic.py`, and get new entries:
```python
                    for x in output_object.histories:
                        if x[2] is None:
                            print(x[1])
```

**Review by Samyak2 — APPROVED** [review]
Thank you for the contribution!

**Pull request merged**
