### PR TITLE
adding history title support

### PR DESCRIPTION
**Pull request by lilaboc**
# Description

I wanted to see history page titles when extracting, so I made this change
But I have trouble fixing a error in test regarding csv sniffing :(

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have read the [contribution guidelines](https://browser-history.readthedocs.io/en/latest/contributing.html) and followed it as far as possible. 
- [X] I have performed a self-review of my own code (if applicable)
- [ ] I have commented my code, particularly in hard-to-understand areas (if applicable)
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] My changes generate no new warnings 
- [ ] I have enabled the pre-commit hook and it's not detecting any issue.
- [ ] Any dependent and pending changes have been merged and published

### CODE REVIEW

**Comment by ObaraEmmanuel** [comment]
@lilaboc I will try and review this. Are you still pursuing it? Sorry for the delay

**Comment by lilaboc** [comment]
@ObaraEmmanuel No worry, I just wanted to scan browser history using title to make sure my son is reading appropriate webpage, thus made this change :)

**Comment by ObaraEmmanuel** [comment]
I have tried running tests locally and a lot of them are failing. You can go through [the contribution guideline](https://browser-history.readthedocs.io/en/latest/contributing.html) to prepare your code for merging to master.

**Comment by lilaboc** [comment]
> I have tried running tests locally and a lot of them are failing. You can go through [the contribution guideline](https://browser-history.readthedocs.io/en/latest/contributing.html) to prepare your code for merging to master.

OK, give me some time to go through and try to fix all the failed tests

**Comment by lilaboc** [comment]
All tests passed, could you please help checking?

**Pull request closed without merging**
