### PR TITLE
Fix failing CI

### PR DESCRIPTION
**Pull request by Samyak2**
# Description

Fixes the failing CI

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have read the [contribution guidelines](https://browser-history.readthedocs.io/en/latest/contributing.html) and followed it as far as possible. 
- [x] I have performed a self-review of my own code (if applicable)
- [x] I have commented my code, particularly in hard-to-understand areas (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings 
- [x] I have enabled the pre-commit hook and it's not detecting any issue.
- [x] Any dependent and pending changes have been merged and published

### CODE REVIEW

**Comment by Samyak2** [comment]
@ObaraEmmanuel looks like the tests are failing on windows. Maybe we forgot to close a file somewhere?

**Comment by Samyak2** [comment]
All issues are now fixed. Existing branches will need to be rebased after this is merged.

**Comment by ObaraEmmanuel** [comment]
> @ObaraEmmanuel looks like the tests are failing on windows. Maybe we forgot to close a file somewhere?

@Samyak2 Funny enough I saw this was fix in #247

**Review by ObaraEmmanuel — APPROVED** [review]
Otherwise, LGTM

**Comment by Samyak2** [comment]
> @Samyak2 Funny enough I saw this fix in #247

That's where I got the fix from xD

**Pull request merged**
