### PR TITLE
[MISC] Move from setup.{cfg,py} to pyproject.toml

### PR DESCRIPTION
**Pull request by Samyak2**
- Moved most of the config from setup.cfg to pyproject.toml
- Moved dev dependencies from just a line in the contributing doc to
  somewhat pinned versions in pyproject.toml
- Moved docs dependencies into pyproject.toml too
- Removed pylint
- Moved flake8 config to a separate file since it does not support
  pyproject.toml yet: https://github.com/PyCQA/flake8/issues/234
- Removed flake8 and black from precommit hooks since pre-commit creates
  a separate env for each check. We don't want different versions of
  them in the pyproject.toml and the pre-commit hooks.
- Updated docs to reflect the new way of developing with pyproject.toml

### CODE REVIEW

**Review by ObaraEmmanuel — COMMENTED** [review]
I have inspected the resulting distribution and it seems tests, docs and package data are getting bundled in. There is a directive not to include package data but it is getting ignored for some reason.

**Comment by Samyak2** [comment]
> I have inspected the resulting distribution and it seems tests, docs and package data are getting bundled in. There is a directive not to include package data but it is getting ignored for some reason.

setuptools-scm was the culprit. It includes all files checked in to git by default. Removed it now. This is the list of files included in the dist (not sure where setup.cfg came from):
```
browser_history-0.4.1/
browser_history-0.4.1/LICENSE
browser_history-0.4.1/MANIFEST.in
browser_history-0.4.1/PKG-INFO
browser_history-0.4.1/README.md
browser_history-0.4.1/browser_history/
browser_history-0.4.1/browser_history/__init__.py
browser_history-0.4.1/browser_history/browsers.py
browser_history-0.4.1/browser_history/cli.py
browser_history-0.4.1/browser_history/generic.py
browser_history-0.4.1/browser_history/utils.py
browser_history-0.4.1/browser_history.egg-info/
browser_history-0.4.1/browser_history.egg-info/PKG-INFO
browser_history-0.4.1/browser_history.egg-info/SOURCES.txt
browser_history-0.4.1/browser_history.egg-info/dependency_links.txt
browser_history-0.4.1/browser_history.egg-info/entry_points.txt
browser_history-0.4.1/browser_history.egg-info/requires.txt
browser_history-0.4.1/browser_history.egg-info/top_level.txt
browser_history-0.4.1/pyproject.toml
browser_history-0.4.1/setup.cfg
```

**Comment by ObaraEmmanuel** [comment]
> (not sure where setup.cfg came from):

I see it when building other projects so I think it is autogenerated.

**Comment by Samyak2** [comment]
I guess it's best to drop python 3.7 now. Many of our dev packages don't support it anymore. And I'm not able to even install the dev dependencies locally with a strange error:

```
❮ pip install -e '.[dev]'
Obtaining file:///Users/samyak/oss/browser-history
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      No `packages` or `py_modules` configuration, performing automatic discovery.
      `flat-layout` detected -- analysing .
      discovered packages -- ['browser_history']
      /private/tmp/pip-build-env-mbvgnpdc/overlay/lib/python3.7/site-packages/setuptools/config/pyprojecttoml.py:66: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        config = read_configuration(filepath, True, ignore_option_errors, dist)
      MemoryError while trying to load entry-point bdist_wheel:

<snip>

        File "/private/tmp/pip-build-env-mbvgnpdc/normal/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 27, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/private/tmp/pip-build-env-mbvgnpdc/normal/lib/python3.7/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/nix/store/31xsz08ix8cdxpp86vy7ngw2nz03rdjd-python3-3.7.17/lib/python3.7/ctypes/__init__.py", line 551, in <module>
          _reset_cache()
        File "/nix/store/31xsz08ix8cdxpp86vy7ngw2nz03rdjd-python3-3.7.17/lib/python3.7/ctypes/__init__.py", line 273, in _reset_cache
          CFUNCTYPE(c_int)(lambda: None)
      MemoryError
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by ObaraEmmanuel** [comment]
Yeah, I totally agree.

**Review by ObaraEmmanuel — COMMENTED** [review]
Screenshot 2024-05-06 201659

Seems test data, `docs` and `.github` are still included with the distribution.

**Comment by Samyak2** [comment]
Hmm weird. I'm not seeing that. These are the commands I'm using:

```
❯ python -m build
❯ tar -tvf dist/browser_history-0.4.1.tar.gz
drwxr-xr-x samyak/staff      0 2024-05-11 11:13 browser_history-0.4.1/
-rw-r--r-- samyak/staff  11345 2023-04-27 09:35 browser_history-0.4.1/LICENSE
-rw-r--r-- samyak/staff     16 2024-05-05 11:36 browser_history-0.4.1/MANIFEST.in
-rw-r--r-- samyak/staff   5803 2024-05-11 11:13 browser_history-0.4.1/PKG-INFO
-rw-r--r-- samyak/staff   4095 2024-05-05 11:36 browser_history-0.4.1/README.md
drwxr-xr-x samyak/staff      0 2024-05-11 11:13 browser_history-0.4.1/browser_history/
-rw-r--r-- samyak/staff   2137 2024-04-20 16:11 browser_history-0.4.1/browser_history/__init__.py
-rw-r--r-- samyak/staff   6833 2024-04-20 16:11 browser_history-0.4.1/browser_history/browsers.py
-rw-r--r-- samyak/staff   8538 2023-10-01 18:06 browser_history-0.4.1/browser_history/cli.py
-rw-r--r-- samyak/staff  27242 2024-04-20 16:49 browser_history-0.4.1/browser_history/generic.py
-rw-r--r-- samyak/staff   6581 2024-04-20 16:11 browser_history-0.4.1/browser_history/utils.py
drwxr-xr-x samyak/staff      0 2024-05-11 11:13 browser_history-0.4.1/browser_history.egg-info/
-rw-r--r-- samyak/staff   5803 2024-05-11 11:13 browser_history-0.4.1/browser_history.egg-info/PKG-INFO
-rw-r--r-- samyak/staff    411 2024-05-11 11:13 browser_history-0.4.1/browser_history.egg-info/SOURCES.txt
-rw-r--r-- samyak/staff      1 2024-05-11 11:13 browser_history-0.4.1/browser_history.egg-info/dependency_links.txt
-rw-r--r-- samyak/staff     61 2024-05-11 11:13 browser_history-0.4.1/browser_history.egg-info/entry_points.txt
-rw-r--r-- samyak/staff    265 2024-05-11 11:13 browser_history-0.4.1/browser_history.egg-info/requires.txt
-rw-r--r-- samyak/staff     16 2024-05-11 11:13 browser_history-0.4.1/browser_history.egg-info/top_level.txt
-rw-r--r-- samyak/staff   1860 2024-05-05 11:41 browser_history-0.4.1/pyproject.toml
-rw-r--r-- samyak/staff     38 2024-05-11 11:13 browser_history-0.4.1/setup.cfg
```

**Review by ObaraEmmanuel — APPROVED** [review]
Turns out I had not deleted the `.egg-info` cache. It looks okay now.

**Pull request merged**
